artifact_uri: localhost:10010/0/c578fb3dfedd4e58a5ea49716cb8c3c6/artifacts
end_time: null
entry_point_name: main
experiment_id: 0
lifecycle_stage: active
name: ''
run_uuid: c578fb3dfedd4e58a5ea49716cb8c3c6
source_name: git@github.com:mlflow/mlflow-example.git
source_type: 3
source_version: 7193f0c7fea755acd68abf8fd6050f5eeeb5e2b3
start_time: 1540451274578
status: 1
tags: []
user_id: ameya
