artifact_uri: localhost:10010/0/66c892481b78466b9dbd7ed7069e54df/artifacts
end_time: null
entry_point_name: main
experiment_id: 0
lifecycle_stage: active
name: ''
run_uuid: 66c892481b78466b9dbd7ed7069e54df
source_name: git@github.com:mlflow/mlflow-example.git
source_type: 3
source_version: 7193f0c7fea755acd68abf8fd6050f5eeeb5e2b3
start_time: 1540451563409
status: 1
tags: []
user_id: ameya
